import { Link } from 'react-router-dom';
import { ArrowRight, BookOpen, Bus, Library, Microscope, ShieldCheck, Trophy } from 'lucide-react';
import { announcements } from '../../data/content';
import { facilityImages, schoolImages, galleryImages, topperImages } from '../../data/images';
import { facilities, school, stats } from '../../data/school';
import { toppers } from '../../data/toppers';

const icons = [ShieldCheck, BookOpen, Microscope, Library, Bus];

export function HomePage() {
  return <>
    <section className="announcement-strip"><div className="container"><strong>Admissions 2026-27</strong><span>{school.admission}</span><Link to="/admission">Apply Online <ArrowRight size={15} /></Link></div></section>
    <section className="hero"><div className="container hero-grid"><div className="hero-copy"><p className="eyebrow">Learning with purpose</p><h1>Build strong foundations. <em>Grow without limits.</em></h1><p>British English School brings together academic focus, practical learning, values and co-curricular opportunities in a calm environment designed for children to learn and thrive.</p><div className="hero-actions"><Link className="btn btn-primary" to="/admission">Begin Admission <ArrowRight size={18} /></Link><Link className="btn btn-outline" to="/about">Discover BES</Link></div></div><div className="hero-visual hero-image-visual"><img src={schoolImages.hero} alt="British English School main campus building" className="hero-campus-image" /><div className="hero-image-overlay" /><div className="hero-card hero-image-card"><span>BES</span><h3>Education for a changing world</h3><p>Academics • Skills • Character • Opportunity</p></div></div></div></section>
    <section className="stats"><div className="container stats-grid">{stats.map(([n, l]) => <div key={l}><strong>{n}</strong><span>{l}</span></div>)}</div></section>
    <section className="section"><div className="container split"><div><p className="eyebrow">About the school</p><h2>A thoughtful start to a lifelong learning journey.</h2><p>From classrooms and laboratories to activity spaces, the school focuses on analytical thinking, problem solving and constructive learning. Students study core subjects while building confidence through a broad range of co-curricular experiences.</p><Link className="text-link" to="/about">Read our story <ArrowRight size={17} /></Link></div><div className="about-photo-card"><img src={schoolImages.campus} alt="British English School students and teachers outside the school building" loading="lazy" /><div><strong>British English School</strong><span>Gere, Manpur, Gaya</span></div></div></div></section>
    <section className="section section-soft"><div className="container"><div className="section-head"><div><p className="eyebrow">School experience</p><h2>Spaces and support for every part of student life.</h2></div><Link className="text-link" to="/facilities">View all facilities <ArrowRight size={17} /></Link></div><div className="facility-grid">{facilities.map((f, i) => { const Icon = icons[i % icons.length]; const image = facilityImages[f]; return <article className="facility-card facility-card-image" key={f}>{image && <img src={image.src} alt={image.alt} loading="lazy" />}<div className="facility-card-body"><Icon /><h3>{f}</h3><span>Explore →</span></div></article>; })}</div></div></section>
    <section className="section"><div className="container message-grid"><article className="message-card director"><div className="message-photo"><img src={schoolImages.director} alt="British English School Director" loading="lazy" /></div><p className="eyebrow">Director's message</p><h3>Education gives direction to ambition.</h3><p>Our focus is to help learners develop knowledge, creativity and the confidence to contribute meaningfully to society.</p><Link to="/about" className="text-link">Read message <ArrowRight size={17} /></Link></article><article className="message-card principal"><div className="message-photo"><img src={schoolImages.principal} alt="British English School Principal" loading="lazy" /></div><p className="eyebrow">Principal's message</p><h3>Prepared for a competitive and changing world.</h3><p>We encourage academic excellence, Indian values, leadership, tolerance and participation across learning, sports and co-curricular activities.</p><Link to="/about" className="text-link">Read message <ArrowRight size={17} /></Link></article></div></section>
    <section className="section section-dark"><div className="container"><div className="section-head light"><div><p className="eyebrow">Student achievement</p><h2>Our toppers, 2025-2026.</h2></div><Trophy /></div><div className="topper-grid">{toppers.slice(0, 6).map(([name, cls, score], i) => <article key={name} className="topper-card topper-card-image"><span>0{i + 1}</span><img src={topperImages[name]} alt={`${name}, Class ${cls}, ${score}`} loading="lazy" /><h3>{name}</h3><p>Class {cls}</p><strong>{score}</strong></article>)}</div><Link className="btn btn-light" to="/toppers">View all toppers</Link></div></section>
    <section className="section"><div className="container"><div className="section-head"><div><p className="eyebrow">Campus moments</p><h2>School life beyond the classroom.</h2></div><Link className="text-link" to="/gallery">Open gallery <ArrowRight size={17} /></Link></div><div className="gallery-mosaic">{galleryImages.slice(0, 8).map((image, i) => <Link to="/gallery" key={`${image.src}-${i}`} className={`gallery-tile tile-${i}`}><img src={image.src} alt={image.alt} loading="lazy" /><span>{image.category}</span></Link>)}</div></div></section>
    <section className="section section-soft"><div className="container announcement-layout"><div><p className="eyebrow">Latest updates</p><h2>Announcements</h2>{announcements.map((a, i) => <article className="announcement" key={a}><b>0{i + 1}</b><p>{a}</p></article>)}<Link className="text-link" to="/announcements">All announcements <ArrowRight size={17} /></Link></div><div className="cta-panel"><img className="admission-cta-image" src={schoolImages.admission} alt="British English School admission open for session 2026-2027" loading="lazy" /><BookOpen /><p className="eyebrow">Admissions</p><h3>Your child's next chapter can start here.</h3><p>Explore admission information and begin the registration process online.</p><Link className="btn btn-primary" to="/admission">Apply for 2026-27</Link></div></div></section>
  </>;
}
